version: "3"

services:
  queue_broker:
    image: rabbitmq:3.9-management
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  server:
    build:
      context: WikiLinkParser
      dockerfile: server.Dockerfile
  worker:
    build:
      context: WikiLinkParser
      dockerfile: worker.Dockerfile
#  client_js:
#    build:
#      context: client-js
