// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: WikiLinkParserService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WikiLinkParserService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_WikiLinkParserService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_WikiLinkParserService_proto_rawDescGZIP(), []int{0}
}

type ConnectionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WikiLinkParserService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_WikiLinkParserService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_WikiLinkParserService_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionStatus) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type ParseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitPage   string `protobuf:"bytes,1,opt,name=initPage,proto3" json:"initPage,omitempty"`
	TargetPage string `protobuf:"bytes,2,opt,name=targetPage,proto3" json:"targetPage,omitempty"`
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WikiLinkParserService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_WikiLinkParserService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_WikiLinkParserService_proto_rawDescGZIP(), []int{2}
}

func (x *ParseRequest) GetInitPage() string {
	if x != nil {
		return x.InitPage
	}
	return ""
}

func (x *ParseRequest) GetTargetPage() string {
	if x != nil {
		return x.TargetPage
	}
	return ""
}

type ParseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceLen uint32 `protobuf:"varint,1,opt,name=traceLen,proto3" json:"traceLen,omitempty"`
	Trace    string `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WikiLinkParserService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_WikiLinkParserService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_WikiLinkParserService_proto_rawDescGZIP(), []int{3}
}

func (x *ParseResponse) GetTraceLen() uint32 {
	if x != nil {
		return x.TraceLen
	}
	return 0
}

func (x *ParseResponse) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

var File_WikiLinkParserService_proto protoreflect.FileDescriptor

var file_WikiLinkParserService_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x57,
	0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x22, 0x0a, 0x0a,
	0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x22, 0x4a, 0x0a,
	0x0c, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6e, 0x69, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x67, 0x65, 0x22, 0x41, 0x0a, 0x0d, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x4c, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x4c, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x32, 0x84, 0x02, 0x0a,
	0x0e, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x12,
	0x53, 0x0a, 0x13, 0x45, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e,
	0x6b, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x1a, 0x20, 0x2e, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0f, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69,
	0x6e, 0x6b, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73,
	0x67, 0x1a, 0x20, 0x2e, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x1c, 0x2e, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e, 0x6b, 0x50,
	0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x75, 0x63, 0x61, 0x72,
	0x64, 0x69, 0x6b, 0x2f, 0x73, 0x6f, 0x61, 0x2d, 0x35, 0x2f, 0x57, 0x69, 0x6b, 0x69, 0x4c, 0x69,
	0x6e, 0x6b, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_WikiLinkParserService_proto_rawDescOnce sync.Once
	file_WikiLinkParserService_proto_rawDescData = file_WikiLinkParserService_proto_rawDesc
)

func file_WikiLinkParserService_proto_rawDescGZIP() []byte {
	file_WikiLinkParserService_proto_rawDescOnce.Do(func() {
		file_WikiLinkParserService_proto_rawDescData = protoimpl.X.CompressGZIP(file_WikiLinkParserService_proto_rawDescData)
	})
	return file_WikiLinkParserService_proto_rawDescData
}

var file_WikiLinkParserService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_WikiLinkParserService_proto_goTypes = []interface{}{
	(*EmptyMsg)(nil),         // 0: WikiLinkParser.EmptyMsg
	(*ConnectionStatus)(nil), // 1: WikiLinkParser.ConnectionStatus
	(*ParseRequest)(nil),     // 2: WikiLinkParser.ParseRequest
	(*ParseResponse)(nil),    // 3: WikiLinkParser.ParseResponse
}
var file_WikiLinkParserService_proto_depIdxs = []int32{
	0, // 0: WikiLinkParser.WikiLinkParser.EstablishConnection:input_type -> WikiLinkParser.EmptyMsg
	0, // 1: WikiLinkParser.WikiLinkParser.AbortConnection:input_type -> WikiLinkParser.EmptyMsg
	2, // 2: WikiLinkParser.WikiLinkParser.PublishTask:input_type -> WikiLinkParser.ParseRequest
	1, // 3: WikiLinkParser.WikiLinkParser.EstablishConnection:output_type -> WikiLinkParser.ConnectionStatus
	1, // 4: WikiLinkParser.WikiLinkParser.AbortConnection:output_type -> WikiLinkParser.ConnectionStatus
	3, // 5: WikiLinkParser.WikiLinkParser.PublishTask:output_type -> WikiLinkParser.ParseResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WikiLinkParserService_proto_init() }
func file_WikiLinkParserService_proto_init() {
	if File_WikiLinkParserService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_WikiLinkParserService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WikiLinkParserService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WikiLinkParserService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WikiLinkParserService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WikiLinkParserService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_WikiLinkParserService_proto_goTypes,
		DependencyIndexes: file_WikiLinkParserService_proto_depIdxs,
		MessageInfos:      file_WikiLinkParserService_proto_msgTypes,
	}.Build()
	File_WikiLinkParserService_proto = out.File
	file_WikiLinkParserService_proto_rawDesc = nil
	file_WikiLinkParserService_proto_goTypes = nil
	file_WikiLinkParserService_proto_depIdxs = nil
}
